dist: trusty
sudo: false
language: node_js

matrix:
    fast_finish: true
    include:
        - node_js: "6"
        - node_js: "8"

before_install:
    - npm i -g npm@5
notifications:
    email: false
